services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dummy_service_1

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dummy_service_2
